# Generated by Django 4.0.4 on 2022-04-19 21:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('datejoined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('lastlogin', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, null=True, upload_to=account.models.get_profile_image_file_path, verbose_name='Profile Image')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('seller_id', models.IntegerField(default=0, verbose_name='Seller Id')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
