# Generated by Django 4.0.4 on 2022-05-28 13:40

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='FirstName')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='LastName')),
                ('datejoined', models.DateTimeField(auto_now_add=True, verbose_name='DateJoined')),
                ('lastlogin', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, null=True, upload_to=account.models.get_profile_image_file_path, verbose_name='Profile Image')),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_token', models.CharField(blank=True, max_length=108, null=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('seller_id', models.IntegerField(default=0, verbose_name='SellerId')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('receiving_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
