# Generated by Django 4.0.4 on 2022-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='addess',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
