# Generated by Django 4.0.4 on 2022-07-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_addess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='addess',
            new_name='address',
        ),
    ]
