# Generated by Django 4.0.4 on 2022-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_selleraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='datejoined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateJoined'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='firstname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='lastlogin',
            field=models.DateTimeField(auto_now=True, verbose_name='LastLogin'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='lastname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='seller_id',
            field=models.IntegerField(default=0, verbose_name='SellerId'),
        ),
    ]
