# Generated by Django 4.0.4 on 2022-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_datejoined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='auth_token',
            field=models.CharField(default='df;ladsjkfsdaljfdsf;dsfds', max_length=108),
        ),
    ]
