# Generated by Django 4.0.4 on 2022-07-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_cartitem_itemcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='itemcart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.cart'),
        ),
    ]
